// import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "../components/Header";
// import Footer from "../components/Footer";
// import { Suspense } from "react";

// // const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Vidora",
//   description: "Nnaedozie dennis movie website",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="bg-slate-950 text-gray-200 overflow-x-hidden font-sans">
//         <Suspense fallback={null}>
//           <Header />
//         </Suspense>
//         <main className="w-full">{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }












import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Suspense } from "react";
import { ClerkProvider } from "@clerk/nextjs"; // ← Add this import

export const metadata: Metadata = {
  title: "Vidora",
  description: "Nnaedozie dennis movie website",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      {" "}
      {/* ← Wrap everything inside ClerkProvider */}
      <html lang="en">
        <body className="bg-slate-950 text-gray-200 overflow-x-hidden font-sans">
          <Suspense fallback={null}>
            <Header />
          </Suspense>
          <main className="w-full">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}





















// import { type Metadata } from "next";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Clerk Next.js Quickstart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton>
//                 <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
//                   Sign Up
//                 </button>
//               </SignUpButton>
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
